services:
  app:
    build: .
    ports:
      - "30112:80"
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}
    volumes:
      - ./database:/var/www/html/database
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./csv:/var/www/html/csv
    restart: unless-stopped
